export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const FETCH_TRASPORT_REQUEST = 'FETCH_TRASPORT_REQUEST';
export const FETCH_TRASPORT_SUCCESS = 'FETCH_TRASPORT_SUCCESS';
export const FETCH_TRASPORT_FAIL = 'FETCH_TRASPORT_FAIL';

export const ADD_TRASPORT_REQUEST = 'ADD_TRASPORT_REQUEST';
export const ADD_TRASPORT_SUCCESS = 'ADD_TRASPORT_SUCCESS';
export const ADD_TRASPORT_FAIL = 'ADD_TRASPORT_FAIL';

export const FETCH_TRANSPORT_BY_ID_REQUEST = 'FETCH_TRANSPORT_BY_ID_REQUEST';
export const FETCH_TRANSPORT_BY_ID_SUCCESS = 'FETCH_TRANSPORT_BY_ID_SUCCESS';
export const FETCH_TRANSPORT_BY_ID_FAIL = 'FETCH_TRANSPORT_BY_ID_FAIL';

export const UPDATE_TRASPORT_REQUEST = 'UPDATE_TRASPORT_REQUEST';
export const UPDATE_TRASPORT_SUCCESS = 'UPDATE_TRASPORT_SUCCESS';
export const UPDATE_TRASPORT_FAIL = 'UPDATE_TRASPORT_FAIL';

export const DELETE_TRASPORT_REQUEST = 'DELETE_TRASPORT_REQUEST';
export const DELETE_TRASPORT_SUCCESS = 'DELETE_TRASPORT_SUCCESS';
export const DELETE_TRASPORT_FAIL = 'DELETE_TRASPORT_FAIL';